name: Example CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.10.0
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.0'
      - name: Install system dependencies
        run: sudo apt-get -y install libxml2-dev libxslt-dev
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.1.3
        with:
          poetry-version: 1.1.11
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      - name: Cache Poetry virtualenv
        uses: actions/cache@v1
        id: cache
        with:
          path: ~/.virtualenvs
          key: poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            poetry-${{ hashFiles('**/poetry.lock') }}
      - name: Set Poetry config
        run: |
          poetry config virtualenvs.in-project false
          poetry config virtualenvs.path ~/.virtualenvs
      - name: Install Dependencies
        run: poetry install
        if: steps.cache.outputs.cache-hit != 'true'
      - name: Check Static Code Tests
        run: |
          make format-check
          make lint
      - name: Running Unit Tests
        run: |
          make test
